### ISSUE TITLE
ghhj

### ISSUE THREAD

**Issue by tuananhbeetech96** [tuananhbeetech96/Demo#3]
```yaml
start_date: 2023/09/20
due_date: 2023/09/20
progress: 0
parent: 
```

Ghnnn
